version: "3.8"

services:
  test:
    image: ${DOCKERHUB_USERNAME}/test:${RELEASE_VERSION}
    ports:
      - 8000:${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
      RELOAD: ${RELOAD}
