name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: uslb2006/test:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          SERVER_PORT: 7000
          RELOAD: ${{ secrets.RELOAD }}
        with:
          host: ${{ secrets.NCP_HOST }}
          port: ${{ secrets.NCP_PORT }}
          username: ${{ secrets.NCP_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: SERVER_PORT, RELOAD
          script: |
            docker pull uslb2006/test:latest
            docker run -d -p 8000:${SERVER_PORT} -e RELOAD -e SERVER_PORT uslb2006/test:latest
