name: Build and Push Docker Image
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test:${{ env.RELEASE_VERSION }}

  Deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          port: ${{ secrets.NCP_PORT }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "deploy/*"
          target: "/root/jw/git-action"

      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          SERVER_PORT: 7000
          RELOAD: ${{ secrets.RELOAD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        with:
          host: ${{ secrets.NCP_HOST }}
          port: ${{ secrets.NCP_PORT }}
          username: ${{ secrets.NCP_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: SERVER_PORT, RELOAD, DOCKERHUB_USERNAME, RELEASE_VERSION
          script: |
            export SERVER_PORT=$SERVER_PORT
            export RELOAD=$RELOAD
            export DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
            export RELEASE_VERSION=$RELEASE_VERSION
            sh /root/jw/git-action/deploy/deploy.sh
