name: CI/CD
on:
  push:
    tags:
      - "v*"
jobs:
  # CI:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     image-tag: ${{ steps.setenv.outputs.tag }}
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - id: setenv
  #       name: Set env
  #       run: echo "::set-output name=tag::${GITHUB_REF#refs/*/v}"

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Login to NCP Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.NCP_ACCESS_KEY }}
  #         password: ${{ secrets.NCP_SECRET_KEY }}
  #         registry: flab-hjw.kr.ncr.ntruss.com

  #     - name: Build and push
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         tags: flab-hjw.kr.ncr.ntruss.com/test:${{ steps.setenv.outputs.tag }}

  CD:
    # needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to NCP Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}
          registry: ${{ secrets.NCP_REG_ENDPOINT }}

      - name: Deploy
        working-directory: ./deploy
        env:
          NCP_HOST:
          SERVER_PORT: 8000
          RELOAD: 0
          # RELEASE_VERSION: ${{ needs.CI.outputs.image-tag }}
          RELEASE_VERSION: 1.1.4
          NCP_DOCKER_HOST: ${{ secrets.NCP_HOST }}
          NCP_DOCKER_PORT: ${{ secrets.NCP_DOCKER_PORT }}
          CA_CERT: ${{ secrets.DOCKER_CA_CERT }}
          CERT: ${{ secrets.DOCKER_CERT }}
          KEY: ${{ secrets.DOCKER_KEY }}
        run: |
          echo $CA_CERT >> ca_cert.pem
          echo $CERT >> cert.pem
          echo $KEY >> key.pem
          docker --tlscacert=ca_cert.pem --tlscert=cert.pem --tlskey=key.pem --tlsverify -H ${NCP_DOCKER_HOST}:${NCP_DOCKER_PORT} ps
